language: php

# lock distro so new future defaults will not break the build
dist: trusty

jobs:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4

install:
  - composer install

script:
  - if [[ "$TRAVIS_PHP_VERSION" > "7.2" ]]; then vendor/bin/phpunit --coverage-text; fi
  - if [[ "$TRAVIS_PHP_VERSION" < "7.3" ]]; then vendor/bin/phpunit --coverage-text -c phpunit.xml.legacy; fi
